CREATE TABLE TBLUSUARIOS
(
  ID_USUARIO integer generated by default as identity primary key,
  NOME_USUARIO varchar(100),
  LOGIN varchar(20),
  SENHA varchar(8),
  TIPO integer REFERENCES TBLTIPOS(ID_TIPO)
  
);