SET TERM ^ ;
ALTER PROCEDURE USPCONSULTARCONTRATOSPORID (
    IDDOCONTRATO integer )
RETURNS (
    ID_CONTRATO integer,
    CONTRATO_ADITIVO varchar(1),
    ID_MODALIDADE varchar(100),
    NUMERO_CONTRATO varchar(20),
    NUMERO_LICITACAO varchar(20),
    ANO_EXERCICIO varchar(4),
    DATA_INICIO date,
    DATA_FINAL date,
    ARQUIVO_CONTRATO varchar(255),
    HISTORICO_CONTRATO blob sub_type 1,
    VALOR_CONTRATO decimal(18,2),
    SALDO_CONTRATO decimal(18,2),
    ID_ORGAO varchar(100),
    ID_FORNECEDOR varchar(100),
    ID_GENERO varchar(100),
    ID_USUARIO varchar(100) )
AS
BEGIN
  
  FOR select 
    ID_CONTRATO, CONTRATO_ADITIVO, ID_MODALIDADE, NUMERO_CONTRATO, NUMERO_LICITACAO, ANO_EXERCICIO, DATA_INICIO, DATA_FINAL, 
    ARQUIVO_CONTRATO, HISTORICO_CONTRATO, VALOR_CONTRATO, SALDO_CONTRATO, ID_ORGAO, ID_FORNECEDOR,
    ID_GENERO, ID_USUARIO
  from 
    UVWCONTRATOS
  where 
   ID_CONTRATO LIKE :IdDoContrato order by NUMERO_CONTRATO
  into :ID_CONTRATO, :CONTRATO_ADITIVO, :ID_MODALIDADE, :NUMERO_CONTRATO, :NUMERO_LICITACAO, :ANO_EXERCICIO, :DATA_INICIO, :DATA_FINAL, 
    :ARQUIVO_CONTRATO, :HISTORICO_CONTRATO, :VALOR_CONTRATO, :SALDO_CONTRATO, :ID_ORGAO, :ID_FORNECEDOR,
    :ID_GENERO, :ID_USUARIO
  DO
  suspend;
END^
SET TERM ; ^


GRANT EXECUTE
 ON PROCEDURE USPCONSULTARCONTRATOSPORID TO  SYSDBA WITH GRANT OPTION;

