SET TERM ^ ;
CREATE PROCEDURE USPCONSULCONTVALORESALDO (
    IDCONTRATO integer )
RETURNS (
    ID_CONTRATO integer,
    CONTRATO_ADITIVO varchar(1),
    VALOR_CONTRATO decimal(18,2),
    SALDO_CONTRATO decimal(18,2) )
AS
BEGIN
  
  FOR select 
    ID_CONTRATO, VALOR_CONTRATO, SALDO_CONTRATO, CONTRATO_ADITIVO
  from 
    TBLCONTRATOS
  where 
    ID_CONTRATO like :IdContrato
  into :ID_CONTRATO, :VALOR_CONTRATO, :SALDO_CONTRATO, :CONTRATO_ADITIVO
  DO
  suspend;
END^
SET TERM ; ^