CREATE VIEW UVWBAIXAITENSPORIDS (ID_BAIXAITEM, ID_ITEM, NUMERO_NOTA, DATA_BAIXAITEM, 
QTDE_BAIXAITEM, VALOR_BAIXA, QTDESALDO_BAIXAITEM, SALDO_BAIXAITEM, ID_CONTRATO, ID_DEPARTAMENTO, 
ID_PRODUTO, ID_USUARIO)
AS select b.ID_BAIXAITEM, b.ID_ITEM, b.NUMERO_NOTA, b.DATA_BAIXAITEM, b.QTDE_BAIXAITEM,
b.VALOR_BAIXA, b.QTDESALDO_BAIXAITEM, b.SALDO_BAIXAITEM, b.ID_CONTRATO, d.NOME_DEPARTAMENTO, 
p.DESCRICAO, b.ID_USUARIO
from TBLBAIXAITENS b, TBLDEPARTAMENTOS d, TBLPRODUTOS p
where b.ID_PRODUTO like p.ID_PRODUTO and b.ID_DEPARTAMENTO like d.ID_DEPARTAMENTO;