CREATE VIEW UVWCONTRATOS (ID_CONTRATO, CONTRATO_ADITIVO, ID_MODALIDADE, NUMERO_CONTRATO, NUMERO_LICITACAO, ANO_EXERCICIO, 
DATA_INICIO, DATA_FINAL, ARQUIVO_CONTRATO, HISTORICO_CONTRATO, VALOR_CONTRATO, SALDO_CONTRATO, 
ID_ORGAO, ID_FORNECEDOR, ID_GENERO, ID_USUARIO, CONTRATO_BYTE)
AS select c.ID_CONTRATO, c.CONTRATO_ADITIVO ,m.NOME_MODALIDADE, c.NUMERO_CONTRATO, c.NUMERO_LICITACAO, c.ANO_EXERCICIO, 
c.DATA_INICIO, c.DATA_FINAL, c.ARQUIVO_CONTRATO, c.HISTORICO_CONTRATO, c.VALOR_CONTRATO, c.SALDO_CONTRATO, 
o.NOME_ORGAO, f.RAZAO_SOCIAL, g.NOME_GENERO, u.NOME_USUARIO, c.CONTRATO_BYTE
from TBLCONTRATOS c, TBLMODALIDADES m, TBLORGAOS o, TBLFORNECEDORES f, TBLGENEROS g, TBLUSUARIOS u
where c.ID_MODALIDADE like m.ID_MODALIDADE and c.ID_ORGAO like o.ID_ORGAO and c.ID_FORNECEDOR like f.ID_FORNECEDOR
 and c.ID_GENERO like g.ID_GENERO and c.ID_USUARIO like u.ID_USUARIO;

