CREATE VIEW UVWDEPARTAMENTOS (ID_DEPARTAMENTO, NOME_DEPARTAMENTO, ENDERECO_DEPARTAMENTO, TEL_FIXO_DEPARTAMENTO, 
ID_BAIRRO, ID_CIDADE, ID_ESTADO, ID_ORGAO)
AS select d.ID_DEPARTAMENTO, d.NOME_DEPARTAMENTO, d.ENDERECO_DEPARTAMENTO, d.TEL_FIXO_DEPARTAMENTO, 
b.NOME_BAIRRO, c.NOME_CIDADE, e.NOME_ESTADO, o.NOME_ORGAO
from TBLDEPARTAMENTOS d, TBLBAIRROS b, TBLCIDADES c, TBLESTADOS e, TBLORGAOS o
where d.ID_BAIRRO like b.ID_BAIRRO and d.ID_CIDADE like c.ID_CIDADE and d.ID_ESTADO like e.ID_ESTADO and 
d.ID_ORGAO like o.ID_ORGAO;
