CREATE VIEW UVWDEPARTPORORGAO (ID_DEPARTAMENTO, NOME_DEPARTAMENTO, ID_ORGAO)
AS select d.ID_DEPARTAMENTO, d.NOME_DEPARTAMENTO, o.NOME_ORGAO
from TBLDEPARTAMENTOS d, TBLORGAOS o
where d.ID_ORGAO like o.ID_ORGAO;