CREATE VIEW UVWFORNECEDORES (ID_FORNECEDOR, RAZAO_SOCIAL, NOME_FANTASIA, CPF_CNPJ, ENDERECO_FORNECEDOR, 
TEL_FIXO_FORNECEDOR, TEL_CEL_FORNECEDOR, ID_BAIRRO, ID_CIDADE, ID_ESTADO, CONTATO, EMAIL_FORNECEDOR)
AS select f.ID_FORNECEDOR, f.RAZAO_SOCIAL, f.NOME_FANTASIA, f.CPF_CNPJ, f.ENDERECO_FORNECEDOR, 
f.TEL_FIXO_FORNECEDOR, f.TEL_CEL_FORNECEDOR, b.NOME_BAIRRO, c.NOME_CIDADE, e.NOME_ESTADO, f.CONTATO, f.EMAIL_FORNECEDOR
from TBLFORNECEDORES f, TBLBAIRROS b, TBLCIDADES c, TBLESTADOS e
where f.ID_BAIRRO like b.ID_BAIRRO and f.ID_CIDADE like c.ID_CIDADE and f.ID_ESTADO like e.ID_ESTADO;
