CREATE VIEW UVWITENSPORIDCONTEDEP (ID_ITEM, QTDE_ITEM, PRECO_UNITARIO, PRECO_TOTAL, NUMERO_ITEM, 
DATA_ITEM, SALDO_ITEM, QTDE_SALDOITEM, ID_CONTRATO, ID_PRODUTO, ID_DEPARTAMENTO, ID_GENERO, ID_USUARIO)
AS select i.ID_ITEM, i.QTDE_ITEM, i.PRECO_UNITARIO, i.PRECO_TOTAL, i.NUMERO_ITEM, i.DATA_ITEM,
i.SALDO_ITEM, i.QTDE_SALDOITEM, i.ID_CONTRATO, p.DESCRICAO, d.NOME_DEPARTAMENTO, g.NOME_GENERO, i.ID_USUARIO
from TBLITENSCONTRATOS i, TBLPRODUTOS p, TBLDEPARTAMENTOS d, TBLGENEROS g
where i.ID_PRODUTO like p.ID_PRODUTO and i.ID_DEPARTAMENTO like d.ID_DEPARTAMENTO and i.ID_GENERO like g.ID_GENERO;
