CREATE VIEW UVWPRODUTOSITENS (ID_PRODUTO, PRODUTO, ID_GENERO)
AS select p.ID_PRODUTO, p.DESCRICAO||' | '||p.DETALHE||' | '||u.LEGENDA||' | '||m.NOME_MARCA, g.NOME_GENERO 
from TBLPRODUTOS p, TBLUNIDMEDIDAS u, TBLMARCAS m, TBLGENEROS g
where p.ID_UNIDMEDIDA like u.ID_UNIDMEDIDA and p.ID_MARCA like m.ID_MARCA and p.ID_GENERO like g.ID_GENERO;
