CREATE VIEW UVWPRODUTOS (ID_PRODUTO, DESCRICAO, DETALHE, ID_MARCA, ID_UNIDMEDIDA, ID_GENERO)
AS select p.ID_PRODUTO, p.DESCRICAO, p.DETALHE, m.NOME_MARCA, u.DESCRICAO, g.NOME_GENERO
from TBLPRODUTOS p, TBLUNIDMEDIDAS u, TBLMARCAS m, TBLGENEROS g
where p.ID_UNIDMEDIDA like u.ID_UNIDMEDIDA and p.ID_MARCA like m.ID_MARCA and p.ID_GENERO like g.ID_GENERO;
