CREATE VIEW UVWUSUARIOS (ID_USUARIO, NOME_USUARIO, LOGIN, SENHA, TIPO)
AS select u.ID_USUARIO, u.NOME_USUARIO, u.LOGIN, u.SENHA, t.NOME_TIPO
from TBLUSUARIOS u, TBLTIPOS t
where u.TIPO like t.ID_TIPO;